version: "3.9"

services:
      www:
            build: php
            container_name: www_3ptitschat
            ports:
                  - "8742:80"
            volumes:
                  - ./php/vhosts:/etc/apache2/sites-enabled
                  - ./:/var/www
            restart: always
            networks:
                  - dev

      db:
            image: mysql
            container_name: db_3ptitschat
            restart: always
            volumes:
                  - db-3ptitschat-data:/var/lib/mysql
            environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            networks:
                  - dev

      phpmyadmin:
            image: phpmyadmin
            container_name: phpmyadmin_3ptitschat
            restart: always
            depends_on:
                  - db
            ports:
                  - 8088:80
            environment:
                  PMA_HOST: db
            networks:
                  - dev

      maildev:
            image: maildev/maildev
            container_name: maildev_3ptitschat
            command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
            ports:
                  - "8082:80"
            restart: always
            networks:
                  - dev

      reactapp:
            build:
                  context: ./react
                  dockerfile: Dockerfile
            container_name: reactapp_3ptitschat
            ports:
                  - "3000:3000"
            volumes:
                  - ./react:/app
            environment:
                  - NODE_ENV=development
            command: npm start
            restart: always
            networks:
                  - dev

networks:
      dev:


volumes:
      db-3ptitschat-data:


